# Generated by Django 3.1.4 on 2020-12-13 12:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passagem',
            name='informacoes',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
